import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import 'antd/dist/reset.css';
import '@/app/globals.css';
import { NotificationProvider } from "@/components/notification/notification";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "@Tai Luong Build Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotificationProvider>
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </NotificationProvider>


      </body>
    </html>
  );
}
